[package]
name = "msdftext"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"

[dependencies]
rustybuzz = "0.20.1"
wgpu = "30.0.0"
winit = "0.30"
anyhow = "1.0"
log = "0.4"
cfg-if = "1.0"
rfd = "0.17.2"
bytemuck = "1.25.2"

# desktop
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"
pollster = "0.4"

[target.'cfg(target_os = "android")'.dependencies]
winit = { version = "0.30", features = ["android-game-activity"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]

wgpu = { version = "30.0.0", features = ["webgl"]}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
getrandom = { version = "0.4", features = ["wasm_js"] }
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
web-sys = { version = "0.3.95", features = [
    "Window",
    "Document",
    "HtmlElement",
    "Text",
] }
